//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: reltrans Created :
// Initializer: reltrans.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "reltransFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Reltrans_Init(Tcl_Interp* tclInterp);
extern "C" int Reltrans_SafeInit(Tcl_Interp* tclInterp);

int Reltrans_Init(Tcl_Interp* tclInterp)
{
        return Reltrans_SafeInit(tclInterp);
}

int Reltrans_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "reltrans";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createreltransFunctionMap();
        XSModelFunction::updateComponentList
              ("/Data/adamingram/Dropbox/Lamppost/UptoDateCode/reverberation_code/lmodel_relxill.dat");
        return TCL_OK;

}

