subroutine allocate_arrays(nlp,nphi,nro,nf,nfsave,nexsave,nlpsave,me,xe)
    use dyn_gr
    use dyn_en
    use conv_mod 
    implicit none
    integer :: nphi,nro,nf,nfsave,nexsave,me,xe,nlp,nlpsave!,nex,nex_conv,nec
 
    !Allocate dynamically the array to calculate the trasfer function 
    if (.not. allocated(re1      )) allocate(re1   (nphi,nro))
    if (.not. allocated(taudo1   )) allocate(taudo1(nphi,nro))
    if (.not. allocated(pem1     )) allocate(pem1  (nphi,nro))
    
    if (nex .ne. nexsave .or. nf .ne. nfsave .or. nlp .ne. nlpsave) then
        !print*,"check",nex,nexsave,nf,nfsave,nlp,nlpsave,allocated(earx)
        if (allocated(earx)) then
            !arrays for time-averaged spectrum and reverberation 
            deallocate(earx)
            deallocate(contx)
            deallocate(absorbx)
            deallocate(photerx)      
            deallocate(photarx)
            deallocate(reline_w0)
            deallocate(imline_w0)   
            deallocate(ker_W0)
            deallocate(ReW0)
            deallocate(ImW0)
            deallocate(re_phot)
            deallocate(im_phot)           
            !arrays for non-linear effects
            deallocate(photarx_1)
            deallocate(photarx_2)
            deallocate(photarx_delta)
            deallocate(photarx_dlogxi)
            deallocate(reline_w1)
            deallocate(imline_w1)
            deallocate(ker_w1)
            deallocate(ReW1)
            deallocate(ImW1)
            deallocate(re_phot_delta)
            deallocate(im_phot_delta)
            deallocate(reline_w2)
            deallocate(imline_w2)
            deallocate(ReW2)
            deallocate(ImW2)
            deallocate(ker_w2)
            deallocate(reline_w3)
            deallocate(imline_w3)
            deallocate(ker_w3)
            deallocate(ReW3)
            deallocate(ImW3)
            deallocate(re_phot_logxi)
            deallocate(im_phot_logxi)
            !arrays for total output
            deallocate(ReSraw)
            deallocate(ImSraw)
            deallocate(ReSrawa)
            deallocate(ImSrawa)
            deallocate(ReGrawa)
            deallocate(ImGrawa)
            deallocate(ReG)     
            deallocate(ImG)   
            deallocate(ReGbar)     
            deallocate(ImGbar)       
        endif
        !allocate arrays that depend on energy 
        allocate(earx(0:nex))   
        allocate(contx(nex,nlp))        
        allocate(absorbx(nex)) 
        allocate(photerx(nex))
        allocate(photarx(nex))  
        allocate(reline_w0(nlp,nex))
        allocate(imline_w0(nlp,nex))        
        allocate(ker_W0(nlp,nex,nf,me,xe))  
        allocate(ReW0(nlp,nex,nf))
        allocate(ImW0(nlp,nex,nf))   
        allocate(re_phot(nex))
        allocate(im_phot(nex))   
        !arrays for non-linear effects 
        allocate(photarx_1(nex))
        allocate(photarx_2(nex))
        allocate(photarx_delta(nex))
        allocate(photarx_dlogxi(nex))
        allocate(reline_w1(nlp,nex))
        allocate(imline_w1(nlp,nex))
        allocate(ker_W1(nlp,nex,nf,me,xe)) 
        allocate(ReW1(nlp,nex,nf))
        allocate(ImW1(nlp,nex,nf))
        allocate(re_phot_delta(nex))
        allocate(im_phot_delta(nex))      
        allocate(reline_w2(nlp,nex))
        allocate(imline_w2(nlp,nex))
        allocate(ker_W2(nlp,nex,nf,me,xe)) 
        allocate(ReW2(nlp,nex,nf))
        allocate(ImW2(nlp,nex,nf))
        allocate(reline_w3(nlp,nex))
        allocate(imline_w3(nlp,nex))
        allocate(ker_W3(nlp,nex,nf,me,xe)) 
        allocate(ReW3(nlp,nex,nf))
        allocate(ImW3(nlp,nex,nf))  
        allocate(re_phot_logxi(nex))    
        allocate(im_phot_logxi(nex))
        !arrays for total output
        allocate(ReSraw(nex,nf))
        allocate(ImSraw(nex,nf))
        allocate(ReSrawa(nex,nf))
        allocate(ImSrawa(nex,nf))
        allocate(ReGrawa(nex,nf))
        allocate(ImGrawa(nex,nf))
        allocate(ReG(nex,nf))     
        allocate(ImG(nex,nf)) 
        allocate(ReGbar(nex))     
        allocate(ImGbar(nex)) 
    end if
    
end subroutine allocate_arrays
